/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newstart;

import javax.swing.JOptionPane;

/**
 *
 * @author vivek
 */
public class foodie1 extends javax.swing.JFrame {

    /**
     * Creates new form foodie1
     */
    public foodie1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        po = new javax.swing.JButton();
        cto = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        net = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel1.setText("FOOD PANDA WELCOME'S YOU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 605, -1));

        jLabel2.setFont(new java.awt.Font("Brush Script MT", 1, 24)); // NOI18N
        jLabel2.setText("FAST FOOD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 43));

        jLabel4.setFont(new java.awt.Font("Brush Script MT", 1, 24)); // NOI18N
        jLabel4.setText("  PURE   VEG  COMBO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 277, -1));

        a.setEditable(false);
        a.setFont(new java.awt.Font("Tempus Sans ITC", 2, 18)); // NOI18N
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 360, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 51));
        jLabel3.setText("TOTAL PRICE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 140, 43));

        b.setEditable(false);
        b.setFont(new java.awt.Font("Tempus Sans ITC", 2, 18)); // NOI18N
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 140, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 51));
        jLabel5.setText("TOTAL PRICE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 353, 130, 40));

        c.setEditable(false);
        c.setFont(new java.awt.Font("Tempus Sans ITC", 2, 18)); // NOI18N
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 423, 150, 30));

        po.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        po.setForeground(new java.awt.Color(51, 153, 255));
        po.setText("PLACE ORDER");
        po.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), new java.awt.Color(51, 255, 255)));
        po.setContentAreaFilled(false);
        po.setEnabled(false);
        po.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poActionPerformed(evt);
            }
        });
        getContentPane().add(po, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 320, 40));

        cto.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        cto.setForeground(new java.awt.Color(51, 153, 255));
        cto.setText("click to order");
        cto.setToolTipText("PLEASE SELECT FASTFOOD.OR CLICK ORDER BUTTON.");
        cto.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), new java.awt.Color(51, 255, 255)));
        cto.setContentAreaFilled(false);
        cto.setEnabled(false);
        cto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctoActionPerformed(evt);
            }
        });
        getContentPane().add(cto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 276, 36));

        jButton3.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 153, 255));
        jButton3.setText("click to order");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), new java.awt.Color(51, 255, 255)));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 240, 36));

        jList2.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "paneer /chapati", "mixveg/ parantha", "patato/ puri", "ladyfinger/chapati" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 240, 157));

        jList1.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "bhelpuri", "pasta", "piza", "burger" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 164, 157));

        net.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        net.setForeground(new java.awt.Color(51, 153, 255));
        net.setText("NET AMOUNT");
        net.setToolTipText("PLEASE CLICK ON ORDE BUTTON FITST.");
        net.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), new java.awt.Color(51, 255, 255)));
        net.setContentAreaFilled(false);
        net.setEnabled(false);
        net.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netActionPerformed(evt);
            }
        });
        getContentPane().add(net, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 40));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newstart/power-xxl (1).png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 280, 50));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newstart/android-system-back (2).png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 250, 50));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newstart/home-home-icon-90085 (2).png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 290, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newstart/bluewater03.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 810, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

 int Total=0;


 if (jList1.isSelectedIndex(0)==true)
 {
Total=Total+150;
JOptionPane.showMessageDialog(this,"Bhel Puri Ordered Rs.150");
 }
 if (jList1.isSelectedIndex(1)==true)
 {
 Total=Total+300;
JOptionPane.showMessageDialog(this,"Pasta Ordered Rs.300");
 }
 if (jList1.isSelectedIndex(2)==true)
 {
 Total=Total+200;
 JOptionPane.showMessageDialog(this,"Pizza Ordered Rs.200");
 }
 if (jList1.isSelectedIndex(3)==true)
 {
 Total=Total+180;
 JOptionPane.showMessageDialog(this,"Burger Ordered Rs.180");
 }
    cto.setEnabled(true);
     
 a.setText(""+Total);
 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ctoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctoActionPerformed
int Total=0;


 if (jList2.isSelectedIndex(0)==true)
 {
Total=Total+300;
JOptionPane.showMessageDialog(this,"paneer /chapati Ordered Rs.300");
 }
 if (jList2.isSelectedIndex(1)==true)
 {
 Total=Total+280;
JOptionPane.showMessageDialog(this,"mixveg/ parantha Ordered Rs.280");
 }
 if (jList2.isSelectedIndex(2)==true)
 {
 Total=Total+250;
 JOptionPane.showMessageDialog(this,"patato/ puri Ordered Rs.250");
 }
 if (jList2.isSelectedIndex(3)==true)
 {
 Total=Total+160;
 JOptionPane.showMessageDialog(this,
"ladyfinger/chapati Ordered Rs.160");
 }
    net.setEnabled(true);
     
 b.setText(""+Total);        // TODO add your handling code here:
    }//GEN-LAST:event_ctoActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void netActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netActionPerformed

        int num1=Integer.parseInt(a.getText());
          int num2=Integer.parseInt(b.getText());
          int num3=num1+num2;
         c.setText(""+num3);  
         po.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_netActionPerformed

    private void poActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poActionPerformed
int num3=Integer.parseInt(c.getText());
        JOptionPane.showMessageDialog(this,"YOUR ORDER OF RUPEES  "+num3+"  HAS PLACED SUCCESSFULLY");        // TODO add your handling code here:
    }//GEN-LAST:event_poActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to POWER OFF?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0); }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       foodie form=new foodie();
        this.dispose();
        form.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        home form=new home();
        this.dispose();
        form.setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foodie1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foodie1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foodie1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foodie1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foodie1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JButton cto;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton net;
    private javax.swing.JButton po;
    // End of variables declaration//GEN-END:variables
}
