/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newstart;

import javax.swing.JOptionPane;

/**
 *
 * @author vivek
 */
public class game_crossNKnot extends javax.swing.JFrame {

    /**
     * Creates new form game_crossNKnot
     */
    public game_crossNKnot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        tp1 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        p1button = new javax.swing.JButton();
        t6 = new javax.swing.JTextField();
        tp2 = new javax.swing.JTextField();
        p2button = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        t7.setText(" ");
        t7.setEnabled(false);
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 326, 44, 54));

        t8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        t8.setText(" ");
        t8.setEnabled(false);
        getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 326, 44, 54));

        t5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        t5.setText(" ");
        t5.setEnabled(false);
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 218, 44, 53));

        tp1.setText(" ");
        getContentPane().add(tp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 70, 35));

        t1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        t1.setText(" ");
        t1.setEnabled(false);
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 121, 44, 47));

        t2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        t2.setText(" ");
        t2.setEnabled(false);
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 121, 44, 47));

        t3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        t3.setText(" ");
        t3.setEnabled(false);
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 121, 43, 47));

        t4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        t4.setText(" ");
        t4.setEnabled(false);
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 218, 44, 53));

        t9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        t9.setText(" ");
        t9.setEnabled(false);
        getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 326, 44, 54));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("  1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 77, 44, 33));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("  8");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 282, 44, 33));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("  7");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 282, 44, 33));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("  9");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 282, 107, 33));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("  4");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 174, 44, 33));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("  5");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 174, 44, 33));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("  2");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 77, 44, 33));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("  3");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 77, 43, 33));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("  6");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 174, 107, 33));

        p1button.setBackground(new java.awt.Color(153, 255, 153));
        p1button.setText("PLAYER 1");
        p1button.setEnabled(false);
        p1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1buttonActionPerformed(evt);
            }
        });
        getContentPane().add(p1button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 142, 38));

        t6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        t6.setText(" ");
        t6.setEnabled(false);
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 218, 44, 53));

        tp2.setText(" ");
        getContentPane().add(tp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 70, 35));

        p2button.setBackground(new java.awt.Color(255, 255, 153));
        p2button.setText("PLAYER 2");
        p2button.setEnabled(false);
        p2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2buttonActionPerformed(evt);
            }
        });
        getContentPane().add(p2button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 142, 40));

        jButton2.setBackground(new java.awt.Color(0, 255, 204));
        jButton2.setText("RE-PLAY");
        jButton2.setToolTipText("CLICK TO RESTART THE GAME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 228, 33));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newstart/android-system-back (2).png"))); // NOI18N
        jButton3.setToolTipText("CLICK TO END THE GAME");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 180, 50));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 228, 33));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("CROSS     AND   KNOT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 520, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newstart/home-home-icon-90085 (2).png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 170, 60));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newstart/power-xxl (1).png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 160, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newstart/game back1.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1buttonActionPerformed
        int Input1=Integer.parseInt(tp1.getText());
 if (Input1<1 || Input1>9)
 JOptionPane.showMessageDialog
 (this,"Enter a Valid Position (1..9)");
 else
 {
 if ((Input1==1 && t1.getText().isEmpty()) ||
 (Input1==2 && t2.getText().isEmpty()) ||
 (Input1==3 && t3.getText().isEmpty()) ||
 (Input1==4 && t4.getText().isEmpty()) ||
 (Input1==5 && t5.getText().isEmpty()) ||
 (Input1==6 && t6.getText().isEmpty()) ||
 (Input1==7 && t7.getText().isEmpty()) ||
 (Input1==8 && t8.getText().isEmpty()) ||
 (Input1==9 && t9.getText().isEmpty())
 )
 {
 switch (Input1)
 {
 case 1:t1.setText("X");break;
 case 2:t2.setText("X");break;
 case 3:t3.setText("X");break;
 case 4:t4.setText("X");break;
 case 5:t5.setText("X");break;
 case 6:t6.setText("X");break;
 case 7:t7.setText("X");break;
 case 8:t8.setText("X");break;
 case 9:t9.setText("X");break;
 }
 if((t1.getText().equals("X") &&
     t2.getText().equals("X") &&
     t3.getText().equals("X"))||
    (t4.getText().equals("X") &&
     t5.getText().equals("X") &&
     t6.getText().equals("X"))||
    (t7.getText().equals("X") &&
     t8.getText().equals("X") &&
     t9.getText().equals("X"))||
    (t1.getText().equals("X") &&
     t4.getText().equals("X") &&
     t7.getText().equals("X"))||
    (t2.getText().equals("X") &&
     t5.getText().equals("X") &&
     t8.getText().equals("X"))||
    (t3.getText().equals("X") &&
     t6.getText().equals("X") &&
     t9.getText().equals("X"))||
    (t1.getText().equals("X") &&
     t5.getText().equals("X") &&
     t9.getText().equals("X"))||
    (t3.getText().equals("X") &&
     t5.getText().equals("X") &&
     t7.getText().equals("X"))
 )
 JOptionPane.showMessageDialog(this,"Player 1 Wins");
 else
 if (!t1.getText().isEmpty() &&
 !t2.getText().isEmpty() &&
 !t3.getText().isEmpty() &&
 !t4.getText().isEmpty() &&
 !t5.getText().isEmpty() &&
 !t6.getText().isEmpty() &&
 !t7.getText().isEmpty() &&
 !t8.getText().isEmpty() &&
 !t9.getText().isEmpty())
 JOptionPane.showMessageDialog(this,"It is a DRAW...");
 else
 tp2.setEditable(true);
 
 p1button.setEnabled(false);
 p2button.setEnabled(true);
 tp1.setEditable(false);
 }
 else
 JOptionPane.showMessageDialog
 (this,"Already Occupied Option RE-ENTER (1..9)");
 }tp1.setText(""); 
       // TODO add your handling code here:
    }//GEN-LAST:event_p1buttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 home form=new home();
            this.dispose();
           form.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
t1.setText("");       
t2.setText("");  
t3.setText(""); 
t4.setText("");  
t5.setText("");  
t6.setText("");  
t7.setText("");  
t8.setText("");  
t9.setText("");  
tp1.setEditable(true);  
tp2.setEditable(false);
p1button.setEnabled(true);
p2button.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void p2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2buttonActionPerformed
int Input2=Integer.parseInt(tp2.getText());
 if (Input2<1 || Input2>9)
 JOptionPane.showMessageDialog
 (this,"Enter a Valid Position (1..9)");
 else
 {
 if ((Input2==1 && t1.getText().isEmpty()) ||
 (Input2==2 && t2.getText().isEmpty()) ||
 (Input2==3 && t3.getText().isEmpty()) ||
 (Input2==4 && t4.getText().isEmpty()) ||
 (Input2==5 && t5.getText().isEmpty()) ||
 (Input2==6 && t6.getText().isEmpty()) ||
 (Input2==7 && t7.getText().isEmpty()) ||
 (Input2==8 && t8.getText().isEmpty()) ||
 (Input2==9 && t9.getText().isEmpty())
 )
 {
 switch (Input2)
 {
 case 1:t1.setText("O");break;
 case 2:t2.setText("O");break;
 case 3:t3.setText("O");break;
 case 4:t4.setText("O");break;
 case 5:t5.setText("O");break;
 case 6:t6.setText("O");break;
 case 7:t7.setText("O");break;
 case 8:t8.setText("O");break;
 case 9:t9.setText("O");break;
 }
 if ((t1.getText().equals("O") &&
 t2.getText().equals("O") &&
 t3.getText().equals("O"))||
 (t4.getText().equals("O") &&
 t5.getText().equals("O") &&
 t6.getText().equals("O"))||
 (t7.getText().equals("O") &&
 t8.getText().equals("O") &&
 t9.getText().equals("O"))||
 (t1.getText().equals("O") &&
 t4.getText().equals("O") &&
 t7.getText().equals("O"))||
 (t2.getText().equals("O") &&
 t5.getText().equals("O") &&
t8.getText().equals("O"))||
 (t3.getText().equals("O") &&
 t6.getText().equals("O") &&
t9.getText().equals("O"))||
 (t1.getText().equals("O") &&
 t5.getText().equals("O") &&
 t9.getText().equals("O"))||
 (t3.getText().equals("O") &&
 t5.getText().equals("O") &&
 t7.getText().equals("O"))
 )
 JOptionPane.showMessageDialog(this,"Player 2 Wins");
 else
 if (!t1.getText().isEmpty() &&
 !t2.getText().isEmpty() &&
 !t3.getText().isEmpty() &&
 !t4.getText().isEmpty() &&
 !t5.getText().isEmpty() &&
 !t6.getText().isEmpty() &&
 !t7.getText().isEmpty() &&
 !t8.getText().isEmpty() &&
 !t9.getText().isEmpty() )
JOptionPane.showMessageDialog(this,"It is a DRAW...");
else
 tp1.setEditable(true);
 
p2button.setEnabled(false);
 p1button.setEnabled(true);
 tp2.setEditable(false);
 }
 else
 JOptionPane.showMessageDialog
 (this,"Already Occupied Option RE-ENTER (1..9)");
 } tp2.setText("");
     
    }//GEN-LAST:event_p2buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
tp1.setText(""); 
tp2.setText(""); 
t1.setText("");       
t2.setText("");  
t3.setText(""); 
t4.setText("");  
t5.setText("");  
t6.setText("");  
t7.setText("");  
t8.setText("");  
t9.setText("");  
tp1.setEditable(true);  
tp2.setEditable(false);
p1button.setEnabled(true);
p2button.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  home form=new home();
            this.dispose();
           form.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if (JOptionPane.showConfirmDialog(this, "Are you sure you want to POWER OFF?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0); }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game_crossNKnot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game_crossNKnot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game_crossNKnot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game_crossNKnot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game_crossNKnot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton p1button;
    private javax.swing.JToggleButton p2button;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JTextField tp1;
    private javax.swing.JTextField tp2;
    // End of variables declaration//GEN-END:variables
}
